.\" Generated with Ronnjs 0.3.8
.\" http://github.com/kapouer/ronnjs/
.
.TH "OMXD" "1" "February 2015" "" ""
.
.SH "NAME"
\fBomxd\fR \-\- daemon to maintain a playlist and play it via omxplayer
.
.SH "SYNOPSIS"
 service omxd start|stop|restart
 omxd [\-d]
.
.P
 echo <command> [abs\-path] > /var/run/omxctl
 omxd <command> [rel\-path]
.
.SH "DESCRIPTION"
The omxd daemon plays your playlist even if you\'ve disconnected from your
Raspberry Pi, to allow the easy implementation of various media centre apps\.
After install, omxd is started automatically at boot\.
.
.SH "OPTIONS"
 \-h	Print this help text
 \-d	Start daemon with debug logging enabled
.
.SH "COMMANDS"
omxd listens for commands through the /var/run/omxctl FIFO,
please write one command at a time into it, for example:
.
.P
echo A /home/foo/bar\.mp3 > /var/run/omxctl
.
.P
Playlist commands: Files shall be absolute paths or URLs playable by omxplayer\.
.
.P
 i file	insert to playlist before current item
 a file	add to playlist after current item
 A file	append to end of playlist
 I file	interrupt playlist, play file on default output, then continue playlist
 H file	interrupt playlist, play file on HDMI, then continue playlist
 J file	interrupt playlist, play file on Jack, then continue playlist
 L file	pLay file on default after current item, then continue playlist
 \.	replay current item
 h	change default output to HDMI
 j	change default output to Jack
 n	next
 N	previous
 g num	go to nth track, counted from zero
 d	next directory
 D	previous directory
 x	delete current item from playlist, play next
 x num	delete nth item from playlist, counted from zero
 X	delete entire playlist, terminate playback
 u	toggle between unsorted/sorted playback (shuffle)
.
.P
Other commands control the running omxplayer instance\.
.
.P
 f	forward 30s
 r	rewind  30s
 F	forward 600s
 R	rewind  600s
 p	play/pause
 P	pause playlist, stop omxplayer
 k	next audio stream
 o	next chapter
 m	next subtitle stream
 s	toggle subtitles
 \-	volume down
 +	volume up
.
.P
Client commands:
.
.P
 S	show what\'s playing now
.
.P
Pass additional omxplayer options:
.
.P
 O opts	add omxplayer Options, valid from now on, restart player
 O	clear additional omxplayer Options, restart player
.
.SH "CLIENT MODE"
You can call omxd with the above commands as arguments, it writes them
into /var/run/omxctl, but translates relative paths into absolute ones
and performs commands recursively if you specify a directory as the file\.
.
.SH "FILES"
When you start the omxd daemon as an unprivileged user the files below
will be created in the current directory instead of the locations below,
to allow easier testing\.
.
.IP "" 4
.
.nf
 /var/run/omxctl	FIFO to write commands into
 /var/local/omxplay	playlist file, actual item indicated by >
 /var/log/omxlog	log file
 /etc/omxd\.conf	defines user to run omxplayer: user=foo
 /etc/init\.d/omxd	init script
.
.fi
.
.IP "" 0
.
.P
\|\.