#!/bin/sh
help() {
	err=$1
	cat <<EOF
rpyt - Raspberry Pi YouTube

Use: rpyt [cmd] url

Finds the related stream URL via youtube-dl, and streams it using curl
via FIFO rpyt.fifo to the player, omxplayer or omxd.

Commands:
-J urA	Play URL via omxd on Jack
-H url	Play URL via omxd on HDMI
-I url	Play URL via omxd on current default audio
-l url	Play URL via omxplayer on Jack (-olocal)
-h url	Play URL via omxplayer on HDMI (-ohdmi)
-h	Print this help text
url	Play URL via omxplayer on HDMI (-ohdmi): default
EOF
	exit $err
}

case $1 in
-J) cmd="omxd J"; url=$2;;
-H) cmd="omxd H"; url=$2;;
-I) cmd="omxd I"; url=$2;;
-l) cmd="omxplayer -olocal"; url=$2;;
-h) cmd="omxplayer -ohdmi";  url=$2; [ "$url" ] || help 0;;
*)  cmd="omxplayer -ohdmi";  url=$1; [ "$url" ] || help 1;;
esac

# Cleanup previous run
rm rpyt.fifo 2>/dev/null
rm jar 2>/dev/null

# Convert YouTube link URL into stream URL
which youtube-dl || exit 2
url=`youtube-dl -g --cookies jar --write-thumbnail $url 2>rpyt.log`
[ "$url" ] || exit 3

# Stream from YouTube > curl > FIFO > player
which curl || exit 4
player=`echo $cmd | sed 's/ .*//'`
which $player || exit 5
mkfifo rpyt.fifo
curl -b jar $url >>rpyt.fifo 2>/dev/null &
$cmd rpyt.fifo
